<?php 
echo "<nav class='yellow darken-1'>"; 
echo "<div class='container'> <div class='nav-wrapper'> <a class='button-collapse black-text' data-activates='mobile-nav' href='#' >";
echo "        <i class='material-icons'>menu</i></a>";
echo "      <ul class='right hide-on-med-and-down'>";
echo "        <li><a data-activates='lf-dropdown' class='dropdown-button black-text' href='#!'>Large Format<i class='material-icons right'>arrow_drop_down</i></a></li>";
echo "        <li><a data-activates='off-dropdown' class='dropdown-button black-text' href='#!'>Offset<i class='material-icons right'>arrow_drop_down</i></a></li>";
echo "        <li> <a data-activates='gar-dropdown' class='dropdown-button black-text' href='#!'>Garments<i class='material-icons right'>arrow_drop_down</i></a></li>";
echo "        <li><a data-activates='web-dropdown' class='dropdown-button black-text' href='#!'>Websites<i class='material-icons right'>arrow_drop_down</i></a></li>";
echo "        <li><a id='login' href='/login.php' class='btn black waves-effect waves-light'>Login</a></li>";
echo "        <li><a href='/dashboard.php' class=' black-text' id='avatar'><i class='material-icons tiny'>person</i></a></li>";
echo "      </ul>";
echo "      <ul class='side-nav' id='mobile-nav'>";
echo "        <ul class='collapsible collapsible-accordion'>";
echo "          <li>";
echo "            <div class='user-view'>";
echo "              <div class='background'>";
echo "                <img src='/img/bg.jpg' />";
echo "              </div>";
echo "              <a href='/dashboard.php'><i class='material-icons black-text'>person</i></a>";
echo "              <a href='/dashboard.php'><span class='black-text name'>John Doe</span></a>";
echo "              <a href='/dashboard.php'><span class='black-text email'>jdandturk@gmail.com</span></a>";
echo "            </div>";
echo "          </li>";
echo "          <li>";
echo "            <a class='black-text collapsible-header' href='#!'>Large Format<i class='material-icons right'>arrow_drop_down</i></a>";
echo "            <div class='collapsible-body'>";
echo "              <ul>";
echo "                <li class='cyan lighten-4'><a href='/large_format.php'>Large Format</a></li>";
echo "                <li><a href='/large_format/banners.php'>Banners</a></li>";
echo "                <li><a href='/large_format/magnets.php'>Magnets</a></li>";
echo "                <li><a href='/large_format/decals.php'>Decals</a></li>";
echo "                <li><a href='/large_format/vehicle_wraps.php'>Vehicle Wraps</a></li>";
echo "                <li><a href='/large_format/window_perf.php'>Window Perf</a></li>";
echo "                <li><a href='/large_format/displays.php'>Displays</a></li>";
echo "                <li><a href='/large_format/signage.php'>Signage</a></li>";
echo "                <li><a href='/large_format/posters.php'>Posters</a></li>";
echo "              </ul>";
echo "            </div>";
echo "          </li>";
echo "        </ul>";
echo "        <ul class='collapsible collapsible-accordion'>";
echo "          <li>";
echo "            <a class='black-text collapsible-header' href='#!'>Offset<i class='material-icons right'>arrow_drop_down</i></a>";
echo "            <div class='collapsible-body'>";
echo "              <ul>";
echo "                <li class='cyan lighten-4'><a href='/offset.php'>Offest</a></li>";
echo "                <li><a href='/offset/business_cards.php'>Business Cards</a></li>";
echo "                <li><a href='/offset/postcards.php'>Postcards</a></li>";
echo "                <li><a href='/offset/flyers.php'>Flyers</a></li>";
echo "                <li><a href='/offset/invitations.php'>Invitations</a></li>";
echo "                <li><a href='/offset/menus.php'>Menus</a></li>";
echo "              </ul>";
echo "            </div>";
echo "          </li>";
echo "        </ul>";
echo "";
echo "        <ul class='collapsible collapsible-accordion'>";
echo "          <li>";
echo "          <a class='black-text collapsible-header' href='#!'>Garments<i class='material-icons right'>arrow_drop_down</i></a>";
echo "            <div class='collapsible-body'>";
echo "              <ul>";
echo "                <li class='cyan lighten-4'><a href='/garments.php'>Garments</a></li>";
echo "                <li><a href='/garments/silk_screen.php'>Silk Screen</a></li>";
echo "                <li><a href='/garments/embroidery.php'>Embroidery</a></li>";
echo "                <li><a href='/garments/vinyl.php'>Vinyl</a></li>";
echo "              </ul>";
echo "            </div>";
echo "          </li>";
echo "        </ul>";
echo "        <ul class='collapsible collapsible-accordion'>";
echo "          <li>";
echo "            <a class='black-text collapsible-header' href='#!'>Websites<i class='material-icons right'>arrow_drop_down</i></a>";
echo "            <div class='collapsible-body'>";
echo "              <ul>";
echo "                <li class='cyan lighten-4'><a href='/websites.php'>Websites</a></li>";
echo "                <li><a href='/websites/static_sites.php'>Static Websites</a></li>";
echo "                <li><a href='/websites/dynamic_sites.php'>Dynamic Websites</a></li>";
echo "                <li><a href='/websites/e-commerce_sites.php'>E-commerce Sites</a></li>";
echo "                <li><a href='/websites/restaurant_sites.php'>Restaurants</a></li>";
echo "                <li><a href='/websites/blog_sites.php'>Blog Sites</a></li>";
echo "                <li><a href='/websites/applications.php'>Applications</a></li>";
echo "              </ul>";
echo "            </div></li>";
echo "        </ul>";
echo "        <li><a href='/login.php' id='login' class='btn btn-small waves-effect waves-light' style='margin: 0 15px;'>Login</a>";
echo "        </li>";
echo "        <li><a href='/dashboard.php' class=' btn waves-effect waves-light' id='avatar'>User Settings<i class='material-icons white-text'>person</i></a>";
echo "        </li>";
echo "      </ul>";
echo "    </div>";
echo "  </div>";
echo "</nav>";
echo "<ul id='lf-dropdown' class='dropdown-content'>";
echo "  <li class='cyan lighten-4'><a href='/large_format.php'>Large Format</a></li>";
echo "  <li><a href='/large_format/banners.php'>Banners</a></li>";
echo "  <li><a href='/large_format/magnets.php'>Magnets</a></li>";
echo "  <li><a href='/large_format/decals.php'>Decals</a></li>";
echo "  <li><a href='/large_format/vehicle_wraps.php'>Vehicle Wraps</a></li>";
echo "  <li><a href='/large_format/window_perf.php'>Window Perf</a></li>";
echo "  <li><a href='/large_format/displays.php'>Displays</a></li>";
echo "  <li><a href='/large_format/signage.php'>Signage</a></li>";
echo "  <li><a href='/large_format/posters.php'>Posters</a></li>";
echo "</ul>";
echo "<ul id='off-dropdown' class='dropdown-content'>";
echo "  <li class='cyan lighten-4'><a href='/offset.php'>Offset</a></li>";
echo "  <li><a href='/offset/business_cards.php'>Business Cards</a></li>";
echo "  <li><a href='/offset/postcards.php'>Postcards</a></li>";
echo "  <li><a href='/offset/flyers.php'>Flyers</a></li>";
echo "  <li><a href='/offset/invitations.php'>Invitations</a></li>";
echo "  <li><a href='/offset/menus.php'>Menus</a></li>";
echo "</ul>";
echo "<ul id='gar-dropdown' class='dropdown-content'>";
echo "  <li class='cyan lighten-4'><a href='/garments.php'>Garments</a></li>";
echo "  <li><a href='/garments/silk_screen.php'>Silk Screen</a></li>";
echo "  <li><a href='/garments/embroidery.php'>Embroidery</a></li>";
echo "  <li><a href='/garments/vinyl.php'>Vinyl</a></li>";
echo "</ul>";
echo "<ul id='web-dropdown' class='dropdown-content'>";
echo "  <li class='cyan lighten-4'><a href='/websites.php'>Websites</a></li>";
echo "  <li><a href='/websites/static_sites.php'>Static Websites</a></li>";
echo "  <li><a href='/websites/dynamic_sites.php'>Dynamic Websites</a></li>";
echo "  <li><a href='/websites/e-commerce_sites.php'>E-commerce Sites</a></li>";
echo "  <li><a href='/websites/restaurant_sites.php'>Restaurants</a></li>";
echo "  <li><a href='/websites/blog_sites.php'>Blog Sites</a></li>";
echo "  <li><a href='/websites/applications.php'>Applications</a></li>";
echo "</ul>";
?>