<?php $title = "Terms and Conditions" ?>
<?php $description = "Hurry Up Prints terms and conditions" ?>
<?php require('head.php') ?>

<?php include 'header.php' ?>

<div class="container m2a">


  <h4>Terms & Conditions</h4>
  <div class="divider mb2"></div>

  <!-- BREADCRUMBS -->
  <nav class="yellow darken-1 mb2">
    <div class="nav-wrapper ms2">
      <div class="col s12">
        <a href="/" class="breadcrumb grey-text text-lighten-1"><i class="material-icons">home</i></a>
        <a class="breadcrumb black-text">Terms & Conditions</a>
      </div>
    </div>
  </nav>

  <h5>
    TERMS AND CONDITIONS
  </h5>
  <p>
    Welcome to Hurry Up Prints Website. We provide our Website as a service to our customers. Please review
    the following basic rules which constitute our "Terms Of Use & Legal Notices," which govern your use of our
    Website. By using our Website you agree to be bound by the terms and conditions set forth below, and our Privacy
    Policy and all disclaimers or other terms and conditions that appear elsewhere on our Website (collectively this
    "Agreement"). Your use of our Website constitutes your agreement to follow and be bound by this Agreement. If you
    do not agree to be bound by this Agreement, please do not use our Website. Although you may "bookmark" a
    particular
    portion of our Website and thereby bypass the Agreement, your use of (or clicking onto) any portion or page of our
    Website still binds you to the Agreement. Since we may revise the Agreement at any time, we recommend that you
    visit these pages periodically to review the Agreement.
  </p>

  <h5>
    Order Cancellation Policy
  </h5>
  <p>
    Order that are cancelled are subject to a cancellation fee based on the current production status of your job. The
    fees are as follows:
  </p>
  <ul>
    <li>
      $10.00 — PRIOR to a proof being sent.
    </li>
    <li>

      $25.00 — AFTER a proof has been sent, but PRIOR to customer approval.
    </li>
    <li>
      NO REFUND — There will be no refunds of any kind AFTER a job has been approved.
    </li>
  </ul>
  <p>
    ALL REFUNDS WILL BE IN THE FORM OF IN-HOUSE CREDIT!
  </p>

  <h6>
    Other Fees
  </h6>
  <p>
    Jobs may be subject to other fees as follows:
  </p>
  <ul>
    <li>$10.00 — Additional proofs ( per proof beyond the 3 allotted to custom designs ).</li>
    <li>$80.00/hour — Approved artwork alterations; 1/2 hour minimum.</li>
    <li>$10.00 — Re-RIP of any file. (Multi-page products like catalogs subject to higher rates)</li>
    <li>$5.00 — PDF proof on Business Card jobs.</li>
  </ul>
  <p>
    This is not an exhaustive list; other fees may be incurred in special circumstances.
  </p>

  <h5>
    General Information
  </h5>
  <p>
    Any original media (discs, pictures, slides, proofs, etc.) are non-returnable and become our property unless
    pre-arrangements are made. Preferred file type is Adobe PDF. Acceptable applications for Mac & PC include (but are
    not limited to) Adobe Illustrator, Adobe InDesign, Adobe Photoshop and Adobe PDF.
    Additional charges may apply if furnished media are incompatible with our software. We cannot guarantee consistent
    results if files are generated by other applications like Microsoft Publisher. For best results, all rasterized
    files should be converted to CYMK color mode. All fonts must be included or embedded. Images must be flattened
    with CMYK in
    TIFF or EPS format. Proofs will be e-mailed or shipped out within 24 business hours of receipt of files and order
    form.
    Turnaround time begins after receipt of final proof approval. Final approval will only be accepted in written /
    email
    format. No verbal approvals will be accepted. Job is considered complete if within +/- 5%. Quoted prices do not
    include any shipping, handling or sales taxes (if applicable). Prices subject to change without notice. All jobs
    require payment in full upon acceptance of order. Unless other payment terms have been previously arranged and
    account is up to date, your credit card will be charged upon placement of order.
  </p>

  <h5>
    Customer Supplied Proofs
  </h5>
  <p>
    For each job, the customer may be required to supply a color hardcopy proof of their job when placing their order.
    If the job is two-sided, folds or binds (like brochures and catalogs), then a working model (mockup) of the job is
    required to indicate backup, page orientation, folding, binding and page order/assignment. We are not responsible
    for any such errors if a working model is not provided prior to proofing. We are also not responsible for any and
    all errors in the customer's printing job if they select the "Run As Is. No Proof" option.
  </p>

  <h5>
    Right Of Refusal
  </h5>
  <p>
    We reserve the right to refuse service or products to any person or organization.
  </p>

  <h5>
    Turnaround Time
  </h5>
  <p>
    Although we make every possible effort to turn jobs around in the estimated times offered, your job may require
    more time due to unforeseeable or uncontrollable circumstances or finishing services added onto the job. We will
    not credit customers if a job runs past the estimated turnaround time. TURNAROUND TIMES ARE AN ESTIMATE, NOT A
    GUARANTEE!
  </p>

  <h5>
    Proprietary Rights
  </h5>
  <p>
    Unless otherwise noted, all written and/or other materials that are part of our Website, including information,
    images, illustrations, designs, icons, data, software, photographs, graphs, videos, typefaces, graphics, music,
    sounds and other material (collectively "Content"), are protected by copyright, trademark, patent or other
    proprietary rights, and these rights are valid and protected in all forms, media and technologies existing now or
    developed in the future. Except as expressly authorized or licensed, you may not copy, modify, remove, delete,
    augment, add to, publish, transmit, participate in the transfer or sale, lease or rental of, create derivative
    works from or in any way exploit any of the Content, in whole or in part. All Content is copyrighted as a
    collective work under the U.S. and international copyright laws, and we own, to the fullest extent allowed by such
    laws, the copyright in the selection, coordination, arrangement, and enhancement of all Content. Our trademarks,
    logos and other trademarks on our Website are the property of their respective owners and are owned by, licensed
    to, or, where required, used with our permission, and, as such, may not be reproduced, copied, or manipulated in
    any manner without the express, written approval of the trademark owner.
  </p>

  <h5>
    Your Use of Our Website
  </h5>
  <p>
    Our Website and the Content are intended solely for your personal, non-commercial use. You may download or copy
    the Content and/or other downloadable materials displayed on the Website for your personal use only; provided that
    you also retain all copyright, trademark and other proprietary notices contained in the material, do not modify or
    alter the material and do not copy or post the material on any network computer or broadcast the material in any
    media. It is strictly prohibited to modify, transmit, distribute, reuse, repost, "frame" or use the Content for
    public or commercial purposes without written permission from an authorized representative. It is also strictly
    prohibited to download any images of our products which appear on our Website. No right, title or interest in any
    downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not
    reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from,
    sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Website or
    any related intellectual property. You agree that if we, in our sole and unfettered discretion, requests in
    writing that you remove any link or links to our Website, you will promptly do so. You agree that we may, in our
    sole discretion, and at any time, terminate your access to and use of our Website, or any part thereof, with or
    without notice.
  </p>

  <h5>
    Use Of Artwork
  </h5>
  <p>
    You understand and agree that we license photos and other artwork, hereinafter referred to as Images, from various
    Licensors and/or Copyright Holders. We are licensed to use the Images as permitted in their respective license(s).
    These Images are used in our design online templates, hereinafter referred to as Templates. You are required to
    comply with the limitations on how the Images and/or Templates can be used.
  </p>

  <h5>
    You May Not:
  </h5>
  <p>
    Use Images and/or Templates together with pornographic, defamatory, or unlawful content or in such a manner that
    it infringes upon any third party's trademark or intellectual property rights.
  </p>

  <p>
    Use the Images and/or Templates in a way that places any person depicted in the Images and/or Templates in a bad
    light or in a way that they may find offensive - this includes, but is not limited to, the use of Images a) in
    pornography; b) in advertisements or promotional materials for tobacco products; c) in advertisements or
    promotional materials for adult entertainment clubs or similar venues, or for escort services; d) in
    advertisements or promotional materials for dating services; e) in connection with political endorsements; f) in
    advertisements or promotional materials for pharmaceutical or healthcare, herbal or medical products, including,
    but not limited to dietary supplements, digestive aids, herbal supplements, personal hygiene or birth control
    products, if the use implies that the depicted person engages in any immoral or illegal activity or suffers from a
    physical or mental infirmity, ailment or condition.
  </p>

  <p>
    Use any Images and/or Templates (in whole or in part) as a trademark, service mark, logo, or other indication of
    origin, or as part thereof, or to otherwise endorse or imply the endorsement of any goods and/or services.
  </p>

  <p>
    Falsely represent, expressly or by way of reasonable implication, that you or a person other than the copyright
    holder(s) of the Images and/or Templates created the Images and/or Templates.
  </p>

  <p>
    We are required to provide Licensors and/or Copyright Holders with the names of the users who access Images and/or
    Templates. By signing below, you are also confirming that you understand this and are granting us permission to
    provide your name and contact information as may be required. In the event that anything in this section
    contradicts any of the agreements or licenses we have with Licensors and/or Copyright Holders regarding the Images
    and/or Templates, the terms of those agreements shall govern.
  </p>

  <p>
    If you use Images and/or Templates in any way prohibited above or in any agreements between us and Licensors
    and/or Copyright Holders it will result in liability in accordance with the terms of our agreements with Licensors
    and/or Copyright Holders.
  </p>

  <h5>
    NO WARRANTIES; LIMITATION OF LIABILITY
  </h5>
  <p>
    YOUR USE OF AND RELIANCE UPON ANY AND ALL INFORMATION, INCLUDING BUT NOT LIMITED TO THE CONTENT ON THIS WEBSITE IS
    AT YOUR SOLE RISK. SUCH INFORMATION IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE MAKE NO EXPRESS OR
    IMPLIED REPRESENTATIONS, WARRANTIES, OR GUARANTEES WITH REGARD TO THE APPROPRIATENESS, ACCURACY, SUFFICIENCY,
    CORRECTNESS, VERACITY, VALUE, COMPLETENESS, OR TIMELINESS OF SUCH INFORMATION. WE EXPRESSLY DISCLAIM ALL
    WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL WE AND/OR OUR SUPPLIERS
    BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES INCLUDING, WITHOUT
    LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR
    PERFORMANCE OF OUR WEBSITE, WITH THE DELAY OR INABILITY TO USE OUR WEBSITE OR RELATED SERVICES, THE PROVISION OF
    OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED
    THROUGH OUR WEBSITE, OR OTHERWISE ARISING OUT OF THE USE OF OUR WEBSITE, WHETHER BASED ON CONTRACT, TORT OR
    OTHERWISE, EVEN IF WE OR ANY OF OUR SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME
    STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL
    DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF OUR WEBSITE, OR
    WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING OUR WEBSITE.
  </p>

  <h5>
    Security
  </h5>
  <p>
    Tampering with our Website, misrepresenting the identity of a user, using buying agents or conducting fraudulent
    activities on our Website are prohibited. Users are prohibited from violating or attempting to violate the
    security of our Website, including, without limitation, (a) accessing data not intended for such user or logging
    onto a server or an account which the user is not authorized to access; (b) using our Website for unintended
    purposes or trying to change the behavior of our Website; (c) attempting to probe, scan or test the vulnerability
    of a system or network or breach security or authentication measures without proper authorization; (d) attempting
    to interfere with service to any user, host or network, including without limitation via means of submitting a
    virus to our Website, overloading, "flooding," "spamming," "mailbombing" or "crashing"; (f) forging any TCP/IP
    packet header or any part of the header information in any e-mail or newsgroup posting. Violations of system or
    network security may result in civil or criminal liability; or (g) forging communications on behalf of our Website
    (impersonating our Website), or to our Website (impersonating as a legitimate user). Sending unsolicited and
    unauthorized e-mail on our behalf, including promotions and/or advertising of products or services, is expressly
    prohibited. You agree not to use any device, software or routine or data to interfere or attempt to interfere with
    the proper working of our Website or any activity being conducted on this site. You agree, further, not to use or
    attempt to use any engine, software, tool, agent, data or other device or mechanism (including without limitation
    browsers, spiders, robots, avatars or intelligent agents) to navigate or search our Website other than the search
    engine and search agents provided by us (if any) or by generally publicly available and acceptable browsers. If
    and when requested, you agree to provide true, accurate and complete user information to us, and to refrain from
    impersonating or falsely representing your affiliation with any person or entity.
  </p>

  <h5>
    Kids' Privacy
  </h5>
  <p>
    Our Website is intended for use by individuals 13 years of age or older. Our Website is not directed to children
    under the age of 13. Users under the age of 13 must use the assistance of a parent or guardian before they use or
    visit our Website.
  </p>

  <h5>
    Errors, Corrections and Changes
  </h5>
  <p>
    Occasionally there may be information on our Website that contains typographical errors, inaccuracies, or
    omissions that may relate to product descriptions, pricing, and availability. We reserve the right (and we will
    use commercially reasonable efforts) to correct any errors, inaccuracies or omissions. Additionally, we reserve
    the right to change or update information at any time without prior notice.
  </p>

  <h5>
    Information & Content You Submit to Us
  </h5>
  <p>
    By using our Website, you agree that any information (except for purchase information as applicable), materials,
    suggestions, ideas or comments you send to us or any other third party using our Website is not confidential. By
    submitting any solicited or unsolicited information using our Website, you grant to us and our affiliates an
    irrevocable and unrestricted license to use, modify, reproduce, transmit, display and distribute such materials,
    information, suggestions, ideas or comments for any purpose whatsoever, to the extent permitted by law.
  </p>

  <p>
    We are not responsible for the content you provide to us. Specifically, we are not responsible for any content
    that violates trademark, copyright, or other intellectual property rights, including but not limited to the use of
    a union bug. We are not a union shop and are not authorized to print materials with a union bug. If you submit
    content with a union bug, we will not print any such content if the union bug is observed during our quality
    control process. Jobs that violate this union bug policy will automatically forfeit monies collected. Refunds,
    credits, or partial refunds will be at the sole discretion of our company.
  </p>

  <h5>
    Indemnity
  </h5>
  <p>
    You agree to indemnify, defend and hold us harmless, its partners, affiliates, subsidiaries and suppliers from any
    liability, loss, claim and expense (including attorneys' reasonable fees) related to your violation of this
    Agreement. You specifically agree to defend, indemnify, and hold us harmless from any and all claims arising from
    the improper use of trademark, copyright, or other protected material, including but not limited to the use of a
    union bug.
  </p>

  <h5>
    Third Party Websites & Links
  </h5>
  <p>
    Our Website may contain links to other Websites that are not under our control ("Third-Party Websites"). We
    provide links solely for the convenience and information of our Website users. We do not warrant or make any
    representation about the substance, quality, functionality, accuracy, fitness for a particular purpose,
    merchantability or any other representation about any Third-Party Website or its content. A link to a Third-Party
    Website on our Website does not constitute sponsorship, endorsement, approval or responsibility for any
    Third-Party Website. We make no representation or warranty as to any products or services offered on any
    Third-Party Website. The conditions of use and privacy policy of any Third-Party Website may differ substantially
    from the Terms of Use and Legal Notices that apply to your use of our Website. Please review the conditions of use
    for all Third-Party Websites for more information about the terms and conditions that apply to your use of
    Third-Party Websites.
  </p>

  <h5>
    Applicable Law & Other Terms
  </h5>
  <p>
    Our Website is created, operated and controlled in the state Nevada, in the United States of America. The laws
    of the State of Nevada will govern the Agreement without giving effect to any principles or conflicts of laws.
    You hereby consent to the exclusive jurisdiction and venue of courts sitting in Nevada, County of Washoe
    of Nevada in all disputes arising out of or relating to the use of our Website. If any
    part of this Agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not
    limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable
    provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the
    original provision and the remainder of the Agreement shall continue in effect. Unless otherwise specified herein,
    this Agreement constitutes the entire agreement between you and us with respect to our Website, and it supersedes
    all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and us
    with respect to our Website. A printed version of this Agreement and of any notice given in electronic form shall
    be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same
    extent and subject to the same conditions as other business documents and records originally generated and
    maintained in printed form.
  </p>

</div>


<?php include 'footer.php' ?>